# vim: set filetype=yaml.ansible :
---
- name: Generate code for chain microservice topology
  hosts: localhost
  tasks:
    - name: delete directories for each microservice
      ansible.builtin.file:
        path: "../fanout_{{ item }}"
        state: absent
      with_sequence: "start=0 count={{ count | int + 1 }} format=%s"

    - name: delete volume for database
      ansible.builtin.file:
        path: "../db/data/db"
        state: absent
