// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: pb_fanout_0/fanout.proto

package pb_fanout_0

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Fanout_0Client is the client API for Fanout_0 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Fanout_0Client interface {
	GetIds(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
}

type fanout_0Client struct {
	cc grpc.ClientConnInterface
}

func NewFanout_0Client(cc grpc.ClientConnInterface) Fanout_0Client {
	return &fanout_0Client{cc}
}

func (c *fanout_0Client) GetIds(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/fanout_0.fanout_0/GetIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Fanout_0Server is the server API for Fanout_0 service.
// All implementations must embed UnimplementedFanout_0Server
// for forward compatibility
type Fanout_0Server interface {
	GetIds(context.Context, *Req) (*Res, error)
	mustEmbedUnimplementedFanout_0Server()
}

// UnimplementedFanout_0Server must be embedded to have forward compatible implementations.
type UnimplementedFanout_0Server struct {
}

func (UnimplementedFanout_0Server) GetIds(context.Context, *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIds not implemented")
}
func (UnimplementedFanout_0Server) mustEmbedUnimplementedFanout_0Server() {}

// UnsafeFanout_0Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Fanout_0Server will
// result in compilation errors.
type UnsafeFanout_0Server interface {
	mustEmbedUnimplementedFanout_0Server()
}

func RegisterFanout_0Server(s grpc.ServiceRegistrar, srv Fanout_0Server) {
	s.RegisterService(&Fanout_0_ServiceDesc, srv)
}

func _Fanout_0_GetIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fanout_0Server).GetIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fanout_0.fanout_0/GetIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fanout_0Server).GetIds(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

// Fanout_0_ServiceDesc is the grpc.ServiceDesc for Fanout_0 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fanout_0_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fanout_0.fanout_0",
	HandlerType: (*Fanout_0Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIds",
			Handler:    _Fanout_0_GetIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb_fanout_0/fanout.proto",
}
