# vim: set filetype=yaml.ansible :
---
- name: Generate code for chain microservice topology
  hosts: localhost
  vars_files:
    - "./configs/{{ config_file }}.yaml"
  roles:
    - code-gen
    - docker-compose
    - dockerfile
    - k8s
    - save-details
