// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: pb_chain_5/chain.proto

package pb_chain_5

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Chain_5Client is the client API for Chain_5 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Chain_5Client interface {
	GetIds(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
}

type chain_5Client struct {
	cc grpc.ClientConnInterface
}

func NewChain_5Client(cc grpc.ClientConnInterface) Chain_5Client {
	return &chain_5Client{cc}
}

func (c *chain_5Client) GetIds(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/chain_5.Chain_5/GetIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Chain_5Server is the server API for Chain_5 service.
// All implementations must embed UnimplementedChain_5Server
// for forward compatibility
type Chain_5Server interface {
	GetIds(context.Context, *Req) (*Res, error)
	mustEmbedUnimplementedChain_5Server()
}

// UnimplementedChain_5Server must be embedded to have forward compatible implementations.
type UnimplementedChain_5Server struct {
}

func (UnimplementedChain_5Server) GetIds(context.Context, *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIds not implemented")
}
func (UnimplementedChain_5Server) mustEmbedUnimplementedChain_5Server() {}

// UnsafeChain_5Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Chain_5Server will
// result in compilation errors.
type UnsafeChain_5Server interface {
	mustEmbedUnimplementedChain_5Server()
}

func RegisterChain_5Server(s grpc.ServiceRegistrar, srv Chain_5Server) {
	s.RegisterService(&Chain_5_ServiceDesc, srv)
}

func _Chain_5_GetIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Chain_5Server).GetIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain_5.Chain_5/GetIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Chain_5Server).GetIds(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

// Chain_5_ServiceDesc is the grpc.ServiceDesc for Chain_5 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chain_5_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chain_5.Chain_5",
	HandlerType: (*Chain_5Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIds",
			Handler:    _Chain_5_GetIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb_chain_5/chain.proto",
}
