// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: pb_chain_1/chain.proto

package pb_chain_1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Chain_1Client is the client API for Chain_1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Chain_1Client interface {
	GetIds(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
}

type chain_1Client struct {
	cc grpc.ClientConnInterface
}

func NewChain_1Client(cc grpc.ClientConnInterface) Chain_1Client {
	return &chain_1Client{cc}
}

func (c *chain_1Client) GetIds(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/chain_1.Chain_1/GetIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Chain_1Server is the server API for Chain_1 service.
// All implementations must embed UnimplementedChain_1Server
// for forward compatibility
type Chain_1Server interface {
	GetIds(context.Context, *Req) (*Res, error)
	mustEmbedUnimplementedChain_1Server()
}

// UnimplementedChain_1Server must be embedded to have forward compatible implementations.
type UnimplementedChain_1Server struct {
}

func (UnimplementedChain_1Server) GetIds(context.Context, *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIds not implemented")
}
func (UnimplementedChain_1Server) mustEmbedUnimplementedChain_1Server() {}

// UnsafeChain_1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Chain_1Server will
// result in compilation errors.
type UnsafeChain_1Server interface {
	mustEmbedUnimplementedChain_1Server()
}

func RegisterChain_1Server(s grpc.ServiceRegistrar, srv Chain_1Server) {
	s.RegisterService(&Chain_1_ServiceDesc, srv)
}

func _Chain_1_GetIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Chain_1Server).GetIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain_1.Chain_1/GetIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Chain_1Server).GetIds(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

// Chain_1_ServiceDesc is the grpc.ServiceDesc for Chain_1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chain_1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chain_1.Chain_1",
	HandlerType: (*Chain_1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIds",
			Handler:    _Chain_1_GetIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb_chain_1/chain.proto",
}
