# vim: set filetype=yaml.ansible :
---
- name: Prepare docker-compose components
  block:
    - name: Prepare db docker-compose for single db
      when: db.single
      block:
        - name: Create directory for database instance
          ansible.builtin.file:
            path: "./generated/{{ name }}/src/{{ type }}-db"
            state: directory
            mode: "1777"

        - name: Generate mongoScript.js
          ansible.builtin.template:
            src: mongoScript.single_db.js.j2
            dest: ./generated/{{ name }}/src/{{ type }}-db/mongoScript.js
            mode: "1777"

        - name: Generate docker-compose.yaml
          ansible.builtin.template:
            src: docker-compose.single_db.yaml.j2
            dest: "./generated/{{ name }}/docker-compose.yaml"
            mode: "1777"

    - name: Prepare docker-compose for multiple db setup
      when: not db.single
      block:
        - name: Create directory for database volume
          ansible.builtin.file:
            path: "./generated/{{ name }}/src/{{ type }}-{{ item }}-db"
            state: directory
            mode: "1777"
          with_sequence: "start=1 count={{ count }} format=%s"

        - name: Generate mongoScript.js
          ansible.builtin.template:
            src: mongoScript.js.j2
            dest: ./generated/{{ name }}/src/{{ type }}-{{ item }}-db/mongoScript.js
            mode: "1777"
          vars:
            x: "{{ item }}"
          with_sequence: "start=1 count={{ count }} format=%s"

        - name: Generate docker-compose.yaml
          ansible.builtin.template:
            src: docker-compose.yaml.j2
            dest: "./generated/{{ name }}/docker-compose.yaml"
            mode: "1777"
