# vim: set filetype=yaml.ansible :
---
- name: Generate code for chain microservice topology
  hosts: localhost
  tasks:
    - name: Create directories for each microservice
      ansible.builtin.file:
        path: "../chain_{{ item }}"
        state: absent
      with_sequence: "start=1 count={{ count }} format=%s"
