# vim: set filetype=yaml.ansible :
---
- name: Generate code for chain microservice topology
  hosts: localhost
  tasks:
    - name: Prepare directory tree and initialize go mod
      block:
        - name: Create directories for each microservice
          ansible.builtin.file:
            path: "../chain_{{ item }}"
            state: directory
            mode: "1777"
          with_sequence: "start=1 count={{ count }} format=%s"

        - name: Create directories for protocol buffer
          ansible.builtin.file:
            path: "../chain_{{ item }}/pb_chain_{{ item }}"
            state: directory
            mode: "1777"
          with_sequence: "start=1 count={{ count }} format=%s"

        - name: Create directories for mongo code
          ansible.builtin.file:
            path: "../chain_{{ item }}/connections"
            state: directory
            mode: "1777"
          with_sequence: "start=1 count={{ count }} format=%s"

        - name: Initialize go modules
          ansible.builtin.command: "go mod init {{ go.module_base_path }}/chain_{{ item }}"
          args:
            chdir: "../chain_{{ item }}"
            creates: go.mod
          with_sequence: "start=1 count={{ count }} format=%s"

    - name: Prepare source code files
      block:
        - name: Generate proto files from template
          ansible.builtin.template:
            src: ./templates/chain_x.proto.j2
            dest: "../chain_{{ item }}/pb_chain_{{ item }}/chain.proto"
            mode: "1777"
          vars:
            chain_x: "{{ item }}"
          with_sequence: "start=1 count={{ count }} format=%s"

        - name: Generate go files
          ansible.builtin.template:
            src: ./templates/main.go.j2
            dest: "../chain_{{ item }}/main.go"
            mode: "1777"
          vars:
            chain_x: "{{ item }}"
          with_sequence: "start=1 count={{ count }} format=%s"

        - name: copy mongo go files
          ansible.builtin.copy:
            src: ./files/connections/
            dest: "../chain_{{ item }}/connections/"
            mode: "1777"
          with_sequence: "start=1 count={{ count }} format=%s"

    - name: Generate and copy grpc code
      block:
        - name: Run protoc to generate grpc code
          ansible.builtin.command:
          args:
            cmd: "protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative pb_chain_{{ item }}/chain.proto"
            chdir: "../chain_{{ item }}"
            creates: "../chain_{{ item }}/chain.pb.go"
          with_sequence: "start=1 count={{ count }} format=%s"

        - name: Ensure that directory for external grpc files exists
          ansible.builtin.file:
            path: "../chain_{{ item | int + 1 }}/pb_chain_{{ item | int + 1 }}"
            state: directory
            mode: "1777"
          with_sequence: "start=1 count={{ count | int - 1 }} format=%s"

        - name: Copy generated grpc files
          ansible.builtin.copy:
            src: "../chain_{{ item | int + 1 }}/pb_chain_{{ item | int + 1 }}/"
            dest: "../chain_{{ item }}/pb_chain_{{ item | int + 1 }}/"
            mode: "1777"
          with_sequence: "start=1 count={{ count | int - 1 }} format=%s"

    - name: Fetch go modules # and run
      block:
        - name: Tidy go modules
          ansible.builtin.command: "go mod tidy"
          args:
            chdir: "../chain_{{ item }}"
            creates: go.sum
          with_sequence: "start=1 count={{ count }} format=%s"

        # - name: Run go programs
        #   ansible.builtin.shell: "(go run main.go > /dev/null 2>&1 &)"
        #   args:
        #     chdir: "../chain_{{ item }}"
        #   changed_when: true
        #   with_sequence: "start=1 count={{ count }} format=%s"

    - name: Generate docker compose file and build images # and run
      block:
        - name: Generate docker-compose.yaml
          ansible.builtin.template:
            src: ./templates/docker-compose.yaml.j2
            dest: ../docker-compose.yaml
            mode: "1777"
