---
docker_hub_user: hiroki11hanada
type: fanout # chain or fanout
name: test-2
count: 3
go:
  module_base_path: github.com/hanapedia/microservice-topologies
db:
  single: false
  username: root
  password: example
base_service_port: 4000
base_db_port: 27017
root: true
